sudo: required
services:
  - docker

before_install:
  - docker build -t amnkta1990/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amnkta1990/react-test npm test

after_success:
  - docker build -t amnkta1990/multi-client ./client
  - docker build -t amnkta1990/multi-nginx ./nginx
  - docker build -t amnkta1990/multi-server ./server
  - docker build -t amnkta1990/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push amnkta1990/multi-client 
  - docker push amnkta1990/multi-nginx
  - docker push amnkta1990/multi-server
  - docker push amnkta1990/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-831569631458'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY